### ISSUE TITLE
ERROR Asset render failed: styles/highlight.css

### ISSUE THREAD

**Issue by Zhaolin-Yu** [denjones/hexo-theme-chan#6]
[root@VM_110_123_centos ~]# 
[root@VM_110_123_centos ~]# hexo g
INFO  Start processing
INFO  Files loaded in 252 ms
ERROR Asset render failed: styles/highlight.css
Error: /root/themes/chan/source/styles/highlight.styl:17:31
   13| highlight-purple = #8959a8
   14| 
   15| $code-block
   16|   background: highlight-background
   17|   margin: 0 article-padding * -1
-------------------------------------^
   18|   padding: 15px article-padding
   19|   border-style: solid
   20|   border-color: color-border

cannot perform article-padding * -1
    at "$code-block" (/root/themes/chan/source/styles/highlight.styl:14:27)

    at Ident.operate (/root/node_modules/stylus/lib/nodes/node.js:234:15)
    at Ident.operate (/root/node_modules/stylus/lib/nodes/ident.js:155:33)
    at Evaluator.visitBinOp (/root/node_modules/stylus/lib/visitor/evaluator.js:567:28)
    at Evaluator.Visitor.visit (/root/node_modules/stylus/lib/visitor/index.js:28:40)
    at Evaluator.visit (/root/node_modules/stylus/lib/visitor/evaluator.js:156:18)
    at Evaluator.visitExpression (/root/node_modules/stylus/lib/visitor/evaluator.js:630:26)
    at Evaluator.Visitor.visit (/root/node_modules/stylus/lib/visitor/index.js:28:40)
    at Evaluator.visit (/root/node_modules/stylus/lib/visitor/evaluator.js:156:18)
    at Evaluator.visitExpression (/root/node_modules/stylus/lib/visitor/evaluator.js:630:26)
    at Evaluator.Visitor.visit (/root/node_modules/stylus/lib/visitor/index.js:28:40)
    at Evaluator.visit (/root/node_modules/stylus/lib/visitor/evaluator.js:156:18)
    at Evaluator.visitProperty (/root/node_modules/stylus/lib/visitor/evaluator.js:673:22)
    at Evaluator.Visitor.visit (/root/node_modules/stylus/lib/visitor/index.js:28:40)
    at Evaluator.visit (/root/node_modules/stylus/lib/visitor/evaluator.js:156:18)
    at Evaluator.visitBlock (/root/node_modules/stylus/lib/visitor/evaluator.js:706:39)
    at Evaluator.Visitor.visit (/root/node_modules/stylus/lib/visitor/index.js:28:40)
    at Evaluator.visit (/root/node_modules/stylus/lib/visitor/evaluator.js:156:18)
    at Evaluator.visitGroup (/root/node_modules/stylus/lib/visitor/evaluator.js:247:22)
    at Evaluator.Visitor.visit (/root/node_modules/stylus/lib/visitor/index.js:28:40)
    at Evaluator.visit (/root/node_modules/stylus/lib/visitor/evaluator.js:156:18)
    at Evaluator.visitRoot (/root/node_modules/stylus/lib/visitor/evaluator.js:693:27)
    at Evaluator.Visitor.visit (/root/node_modules/stylus/lib/visitor/index.js:28:40)
INFO  Generated: index.html
INFO  Generated: archives/index.html
INFO  Generated: 20161217/Hello-world/index.html
INFO  Generated: archives/2016/12/index.html
INFO  Generated: archives/2016/index.html
INFO  Generated: PhotoSwipe/default-skin/default-skin.png
INFO  Generated: images/cc/by.png
INFO  Generated: styles/highlight.css
INFO  Generated: scripts/main.js
INFO  Generated: PhotoSwipe/photoswipe-ui-default.min.js
INFO  Generated: PhotoSwipe/photoswipe.css
INFO  Generated: styles/archive.css

主题内没有改动过，hexo3.2.2。这是什么问题啊

**Comment by denjones** [comment]
duplicated with #4
